### ISSUE TITLE
Weblink starts fine in cmd, but does't load on the phone.

### ISSUE THREAD

**Issue by smirki** [soylent/weblink#2]
I open Safari and add in the url for weblink, but it doesn't load. What steps can I take to make sure it loads?

**Comment by soylent** [comment]
Hi @smirki Sorry for the trouble.

Please make sure that your devices are on the same local network, i.e. your computer is connected to your phone's hotspot. What URL does weblink print when you start it?  Can you open that URL on any other device (or even locally)?

Also, your firewall might be blocking incoming connections.

**Comment by SMJD11** [comment]
I also have a similar problem. Weblink outputs the url in terminal, but doesn't connect on safari on another device or even locally.
Weblink outputs the link as
http://ip:port/

**Comment by soylent** [comment]
Hi @smirki I've just released a new version of weblink that should fix this problem. Please give it a try:
```sh
$ gem update weblink
$ weblink --version  # this should print v1.1.2
```

**Comment by smirki** [comment]
This works for me, thank you!
