### ISSUE TITLE
Other device unable to open page

### ISSUE THREAD

**Issue by SMJD11** [soylent/weblink#3]
Weblink outputs the url in terminal, but doesn't connect on safari on another device or even locally.
Weblink outputs the link as
http://ip:port/

**Comment by soylent** [comment]
Hi @SMJD11 - sorry for the trouble. Does it output a private IP address, e.g. `172.x.y.z`? Could you post the first two octets (ex. `172.20`)?

**Comment by SMJD11** [comment]
It is 172.20

**Comment by soylent** [comment]
Thanks, the address looks right. Please make sure that ports 8080 and 3128 are not already in use and your firewall is not blocking incoming connections. Does weblink print any error messages in the terminal?

**Comment by SMJD11** [comment]
Weblink is not print any error messages in the terminal and everything seems to be fine.

**Comment by soylent** [comment]
Hi @SMJD11 I've released a new version of weblink that should fix this issue. Please try it:
```sh
$ gem update weblink
$ weblink --version  # this should print v1.1.2
```

**Comment by SMJD11** [comment]
Hello @soylent 

I was able to successfully update weblink. So far it is working as expected. Thank you.
