### ISSUE TITLE
Unable to Load Weblink on Phone

### ISSUE THREAD

**Issue by istp4lmrs** [soylent/weblink#6]
When I initialize weblink, I receive an ip as follows 192.168.xx.x:8080. When I tried accessing the ip on both an android and apple phone, they were not able to access the webpage. Could you please provide guidance on how to fix this issue. I have the latest version of weblink 1.1.2

**Comment by soylent** [comment]
Hi @istp4lmrs! Please make sure that your computer is connected to the hotspot _before_ you start weblink. Normally it should print an address like 172.20.x.x:8080. 

Also, it could be that weblink is not detecting the right interface to listen on. In that case, please send me the output of the following command: `ruby -rsocket -e 'pp Socket.getifaddrs.map { [_1, _1.addr] }'`

**Comment by istp4lmrs** [comment]
Hi Soylent! I did connect to my computer before I started weblink. This is the output from the command. Am I suppose to set the proxy on the windows level or chrome level?

[[#<Socket::Ifaddr ethernet_32778>, nil],
 [#<Socket::Ifaddr wireless_32769>, nil],
 [#<Socket::Ifaddr wireless_32770>, nil],
 [#<Socket::Ifaddr ethernet_32774 UP fe80::646a:95ec:baed:5886%23>, #<Addrinfo: fe80::646a:95ec:baed:5886%23>],
 [#<Socket::Ifaddr ethernet_32774 UP 192.168.65.1>, #<Addrinfo: 192.168.65.1>],
 [#<Socket::Ifaddr ethernet_32775 UP fe80::b492:d955:5cf7:5011%22>, #<Addrinfo: fe80::b492:d955:5cf7:5011%22>],
 [#<Socket::Ifaddr ethernet_32775 UP 192.168.127.1>, #<Addrinfo: 192.168.127.1>],
 [#<Socket::Ifaddr ethernet_32777>, nil],
 [#<Socket::Ifaddr wireless_32768 UP fe80::8a8:ebe2:c4c0:8ef3%21>, #<Addrinfo: fe80::8a8:ebe2:c4c0:8ef3%21>],
 [#<Socket::Ifaddr wireless_32768 UP 192.168.126.180>, #<Addrinfo: 192.168.126.180>],
 [#<Socket::Ifaddr ethernet_32770>, nil],
 [#<Socket::Ifaddr loopback_0 UP,LOOPBACK ::1>, #<Addrinfo: ::1>],
 [#<Socket::Ifaddr loopback_0 UP,LOOPBACK 127.0.0.1>, #<Addrinfo: 127.0.0.1>]]

**Comment by soylent** [comment]
It looks like weblink is not selecting the right address. Can you start weblink and open http://192.168.126.180:8080 on your phone?

**Comment by istp4lmrs** [comment]
Thank you! That seemed to do the trick
